language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - tip
go_import_path: suy.io/bots
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -v -race -show -service=travis-ci ./...
