// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: info.go

package team

import (
	"bytes"
	"encoding/json"
	"fmt"
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *InfoRequest) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *InfoRequest) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"token":`)
	fflib.WriteJsonString(buf, string(j.Token))
	buf.WriteByte('}')
	return nil
}

const (
	ffjtInfoResponsebase = iota
	ffjtInfoResponsenosuchkey

	ffjtInfoResponseTeam
)

var ffjKeyInfoResponseTeam = []byte("team")

// UnmarshalJSON umarshall json - template of ffjson
func (j *InfoResponse) UnmarshalJSON(input []byte) error {
	fs := fflib.NewFFLexer(input)
	return j.UnmarshalJSONFFLexer(fs, fflib.FFParse_map_start)
}

// UnmarshalJSONFFLexer fast json unmarshall - template ffjson
func (j *InfoResponse) UnmarshalJSONFFLexer(fs *fflib.FFLexer, state fflib.FFParseState) error {
	var err error
	currentKey := ffjtInfoResponsebase
	_ = currentKey
	tok := fflib.FFTok_init
	wantedTok := fflib.FFTok_init

mainparse:
	for {
		tok = fs.Scan()
		//	println(fmt.Sprintf("debug: tok: %v  state: %v", tok, state))
		if tok == fflib.FFTok_error {
			goto tokerror
		}

		switch state {

		case fflib.FFParse_map_start:
			if tok != fflib.FFTok_left_bracket {
				wantedTok = fflib.FFTok_left_bracket
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_key
			continue

		case fflib.FFParse_after_value:
			if tok == fflib.FFTok_comma {
				state = fflib.FFParse_want_key
			} else if tok == fflib.FFTok_right_bracket {
				goto done
			} else {
				wantedTok = fflib.FFTok_comma
				goto wrongtokenerror
			}

		case fflib.FFParse_want_key:
			// json {} ended. goto exit. woo.
			if tok == fflib.FFTok_right_bracket {
				goto done
			}
			if tok != fflib.FFTok_string {
				wantedTok = fflib.FFTok_string
				goto wrongtokenerror
			}

			kn := fs.Output.Bytes()
			if len(kn) <= 0 {
				// "" case. hrm.
				currentKey = ffjtInfoResponsenosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			} else {
				switch kn[0] {

				case 't':

					if bytes.Equal(ffjKeyInfoResponseTeam, kn) {
						currentKey = ffjtInfoResponseTeam
						state = fflib.FFParse_want_colon
						goto mainparse
					}

				}

				if fflib.SimpleLetterEqualFold(ffjKeyInfoResponseTeam, kn) {
					currentKey = ffjtInfoResponseTeam
					state = fflib.FFParse_want_colon
					goto mainparse
				}

				currentKey = ffjtInfoResponsenosuchkey
				state = fflib.FFParse_want_colon
				goto mainparse
			}

		case fflib.FFParse_want_colon:
			if tok != fflib.FFTok_colon {
				wantedTok = fflib.FFTok_colon
				goto wrongtokenerror
			}
			state = fflib.FFParse_want_value
			continue
		case fflib.FFParse_want_value:

			if tok == fflib.FFTok_left_brace || tok == fflib.FFTok_left_bracket || tok == fflib.FFTok_integer || tok == fflib.FFTok_double || tok == fflib.FFTok_string || tok == fflib.FFTok_bool || tok == fflib.FFTok_null {
				switch currentKey {

				case ffjtInfoResponseTeam:
					goto handle_Team

				case ffjtInfoResponsenosuchkey:
					err = fs.SkipField(tok)
					if err != nil {
						return fs.WrapErr(err)
					}
					state = fflib.FFParse_after_value
					goto mainparse
				}
			} else {
				goto wantedvalue
			}
		}
	}

handle_Team:

	/* handler: j.Team type=struct { ID string "json:\"id\""; Name string "json:\"name\""; Domain string "json:\"domain\""; EmailDomain string "json:\"email_domain\""; Icon struct { Image34 string "json:\"image_34\""; Image44 string "json:\"image_44\""; Image68 string "json:\"image_68\""; Image88 string "json:\"image_88\""; Image102 string "json:\"image_102\""; Image132 string "json:\"image_132\""; ImageDefault bool "json:\"image_default\"" } "json:\"icon\""; EnterpriseID string "json:\"enterprise_id\""; EnterpriseName string "json:\"enterprise_name\"" } kind=struct quoted=false*/

	{
		/* Falling back. type=struct { ID string "json:\"id\""; Name string "json:\"name\""; Domain string "json:\"domain\""; EmailDomain string "json:\"email_domain\""; Icon struct { Image34 string "json:\"image_34\""; Image44 string "json:\"image_44\""; Image68 string "json:\"image_68\""; Image88 string "json:\"image_88\""; Image102 string "json:\"image_102\""; Image132 string "json:\"image_132\""; ImageDefault bool "json:\"image_default\"" } "json:\"icon\""; EnterpriseID string "json:\"enterprise_id\""; EnterpriseName string "json:\"enterprise_name\"" } kind=struct */
		tbuf, err := fs.CaptureField(tok)
		if err != nil {
			return fs.WrapErr(err)
		}

		err = json.Unmarshal(tbuf, &j.Team)
		if err != nil {
			return fs.WrapErr(err)
		}
	}

	state = fflib.FFParse_after_value
	goto mainparse

wantedvalue:
	return fs.WrapErr(fmt.Errorf("wanted value token, but got token: %v", tok))
wrongtokenerror:
	return fs.WrapErr(fmt.Errorf("ffjson: wanted token: %v, but got token: %v output=%s", wantedTok, tok, fs.Output.String()))
tokerror:
	if fs.BigError != nil {
		return fs.WrapErr(fs.BigError)
	}
	err = fs.Error.ToError()
	if err != nil {
		return fs.WrapErr(err)
	}
	panic("ffjson-generated: unreachable, please report bug.")
done:

	return nil
}
