// Code generated by ffjson <https://github.com/pquerna/ffjson>. DO NOT EDIT.
// source: open.go

package dialog

import (
	fflib "github.com/pquerna/ffjson/fflib/v1"
)

// MarshalJSON marshal bytes to json - template
func (j *OpenRequest) MarshalJSON() ([]byte, error) {
	var buf fflib.Buffer
	if j == nil {
		buf.WriteString("null")
		return buf.Bytes(), nil
	}
	err := j.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// MarshalJSONBuf marshal buff to json - template
func (j *OpenRequest) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
	if j == nil {
		buf.WriteString("null")
		return nil
	}
	var err error
	var obj []byte
	_ = obj
	_ = err
	buf.WriteString(`{"token":`)
	fflib.WriteJsonString(buf, string(j.Token))
	buf.WriteString(`,"trigger_id":`)
	fflib.WriteJsonString(buf, string(j.TriggerID))
	if j.Dialog != nil {
		buf.WriteString(`,"dialog":`)

		{

			err = j.Dialog.MarshalJSONBuf(buf)
			if err != nil {
				return err
			}

		}
	} else {
		buf.WriteString(`,"dialog":null`)
	}
	buf.WriteByte('}')
	return nil
}
